# 3.1 넘파이배열

## 넘파이 패키지 임포트

In [4]:
import numpy as np

## 1차원 배열만들기

In [5]:
ar = np.array([0,1,2,3,4,5,6,7,8,9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(ar)

numpy.ndarray

## 벡터화 연산

In [7]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
answer = []
for di in data:
    answer.append(2 * di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [8]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
L = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(2 * L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [11]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [12]:
2 * a + b

array([12, 24, 36])

In [13]:
a == 2

array([False,  True, False])

In [15]:
b > 10

array([False,  True,  True])

In [16]:
(a==2)&(b>10)

array([False,  True, False])

## 2차원 배열 만들기

In [22]:
c = np.array([[0,1,2],[3,4,5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
len(c)  ##행의 갯수

2

In [26]:
len(c[0])  ##열의 갯수

3

In [28]:
c.shape  ##한번에 행렬크기 알려주는 함수

(2, 3)

In [29]:
d = np.array([c,2*c,3*c])
d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 0,  2,  4],
        [ 6,  8, 10]],

       [[ 0,  3,  6],
        [ 9, 12, 15]]])

In [30]:
len(d)

3

In [32]:
d.shape

(3, 2, 3)

(3, 2, 3)   2X3 행렬이 3개가 있다

<p class="admonition-title">연습 문제 1</p>
<p>넘파이를 사용하여 다음과 같은 행렬을 만든다.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="mi">10</span> <span class="mi">20</span> <span class="mi">30</span> <span class="mi">40</span>
<span class="mi">50</span> <span class="mi">60</span> <span class="mi">70</span> <span class="mi">80</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="id6">

In [37]:
d = np.array([[10,20,30,40],[50,60,70,80]])
d

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 3차원 배열 만들기

In [38]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]]) 

## 배열의 차원과 크기 알아내기

In [40]:
a = np.array([1,2,3])
print(a.ndim)
print(a.shape)

1
(3,)


In [41]:
c = np.array([[0, 1, 2], [3, 4, 5]])
print(c.ndim)
print(c.shape)

2
(2, 3)


## 배열의 인덱싱

다음시간에 합니다