In [1]:
import numpy as np

# 넘파이 배열

## 배열의 인덱싱

찾아 보는것

In [2]:
a = np.array([0,1,2,3,4])

In [3]:
a[2]

2

In [4]:
a[-1]

4

In [5]:
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
a [0,0]

0

In [11]:
a[0,1]

1

In [12]:
a[-1,-1]

5

## 배열의 슬라이싱

In [31]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [15]:
a[0,:]

array([0, 1, 2, 3])

In [16]:
a[:,1]

array([1, 5])

In [17]:
a[1,1:]

array([5, 6, 7])

In [18]:
a[:2,:2]

array([[0, 1],
       [4, 5]])

<p class="admonition-title">연습 문제 2</p>
<p>다음 행렬과 같은 행렬이 있다.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">m</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">array</span><span class="p">([[</span> <span class="mi">0</span><span class="p">,</span>  <span class="mi">1</span><span class="p">,</span>  <span class="mi">2</span><span class="p">,</span>  <span class="mi">3</span><span class="p">,</span>  <span class="mi">4</span><span class="p">],</span>
            <span class="p">[</span> <span class="mi">5</span><span class="p">,</span>  <span class="mi">6</span><span class="p">,</span>  <span class="mi">7</span><span class="p">,</span>  <span class="mi">8</span><span class="p">,</span>  <span class="mi">9</span><span class="p">],</span>
            <span class="p">[</span><span class="mi">10</span><span class="p">,</span> <span class="mi">11</span><span class="p">,</span> <span class="mi">12</span><span class="p">,</span> <span class="mi">13</span><span class="p">,</span> <span class="mi">14</span><span class="p">]])</span>
</pre></div>
</div>
<ol class="simple">
<li><p>이 행렬에서 값 7 을 인덱싱한다.</p></li>
<li><p>이 행렬에서 값 14 을 인덱싱한다.</p></li>
<li><p>이 행렬에서 배열 [6, 7] 을 슬라이싱한다.</p></li>
<li><p>이 행렬에서 배열 [7, 12] 을 슬라이싱한다.</p></li>
<li><p>이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.</p></li>

In [32]:
m = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])

In [33]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
#1
m[1,2]

7

In [38]:
#2
m[-1,-1]

14

In [40]:
#3
m[1,1:3]

array([6, 7])

In [43]:
#4
m[1:,2]

array([ 7, 12])

In [47]:
#5
m[:2,3:]

array([[3, 4],
       [8, 9]])

## 배열 인덱싱

In [22]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
                False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [23]:
a%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [24]:
a%2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [25]:
a[a%2==0]

array([0, 2, 4, 6, 8])

In [26]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [27]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [28]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

특정 열 골라내기

In [30]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

행의 순서 바꾸기

==========================================================

<p class="admonition-title">연습 문제 3</p>
<p>다음 행렬과 같은 배열이 있다.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">x</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">array</span><span class="p">([</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">5</span><span class="p">,</span> <span class="mi">6</span><span class="p">,</span> <span class="mi">7</span><span class="p">,</span> <span class="mi">8</span><span class="p">,</span> <span class="mi">9</span><span class="p">,</span> <span class="mi">10</span><span class="p">,</span>
             <span class="mi">11</span><span class="p">,</span> <span class="mi">12</span><span class="p">,</span> <span class="mi">13</span><span class="p">,</span> <span class="mi">14</span><span class="p">,</span> <span class="mi">15</span><span class="p">,</span> <span class="mi">16</span><span class="p">,</span> <span class="mi">17</span><span class="p">,</span> <span class="mi">18</span><span class="p">,</span> <span class="mi">19</span><span class="p">,</span> <span class="mi">20</span><span class="p">])</span>
</pre></div>
</div>
<ol class="simple">
<li><p>이 배열에서 3의 배수를 찾아라.</p></li>
<li><p>이 배열에서 4로 나누면 1이 남는 수를 찾아라.</p></li>
<li><p>이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.</p></li>

In [49]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [53]:
#1
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [54]:
#2
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [55]:
#3
x[(x % 3 == 0)&(x % 4 == 1)]

array([9])

# 배열의 생성과 변형

## 넘파이의 자료형

In [56]:
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [57]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [58]:
x = np.array([1, 2, 3.0])
x.dtype

dtype('float64')

In [59]:
x = np.array([1, 2, 3], dtype='f')
x.dtype

dtype('float32')

In [60]:
x[0] + x[1]

3.0

In [61]:
x = np.array([1, 2, 3], dtype='U')
x.dtype

dtype('<U1')

In [62]:
x[0] + x[1]

'12'

## Inf와 NaN

In [63]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

<ipython-input-63-6ab12ec6e7a4>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
<ipython-input-63-6ab12ec6e7a4>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [64]:
np.log(0)

<ipython-input-64-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [65]:
np.exp(-np.inf)

0.0

## 배열생성

In [66]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [67]:
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [68]:
c = np.zeros((5, 2), dtype="i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [69]:
d = np.zeros(5, dtype="U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [70]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE"
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [71]:
e = np.ones((2, 3, 4), dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [72]:
f = np.ones_like(b, dtype="f")
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [73]:
g = np.empty((4, 3))
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [74]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
np.arange(3, 21, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

np.arrange(first,last,step)

In [76]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

np.linsapce(first,last,개수)

In [83]:
np.logspace(0, 1, 10)

array([ 1.        ,  1.29154967,  1.66810054,  2.15443469,  2.7825594 ,
        3.59381366,  4.64158883,  5.9948425 ,  7.74263683, 10.        ])

In [85]:
np.log(np.logspace(0, 1, 10))/np.log(10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])