# 배열의 생성과 변형

## 전치연산

In [4]:
import numpy as np

In [5]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## 배열의 크기 변형

In [8]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
b = a.reshape(3,4)

In [10]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
a.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
a.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [13]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
x = np.arange(5)

In [17]:
x

array([0, 1, 2, 3, 4])

In [19]:
x.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [20]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

## 배열연결

In [21]:
a1 = np.ones((2,3))

In [22]:
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
a2 = np.zeros((2,2))
a2

array([[0., 0.],
       [0., 0.]])

In [25]:
np.hstack([a1,a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [26]:
b1 = np.ones((2,3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
b2 = np.zeros((3,3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.vstack([b1,b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
c1 = np.ones((3,4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
c2 = np.zeros((3,4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.dstack([c1,c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [33]:
(np.dstack([c1,c2])).shape

(3, 4, 2)

In [34]:
c = np.stack([c1,c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [35]:
c.shape

(2, 3, 4)

In [36]:
c = np.stack([c1,c2],axis = 1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [37]:
c.shape

(3, 2, 4)

In [38]:
np.r_[np.array([1,2,3]),np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [39]:
np.c_[np.array([1,2,3]),np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [40]:
a = np.array([[0,1,2],[3,4,5]])
np.tile(a,2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [41]:
np.tile(a, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

<p class="admonition-title">연습 문제 3.2.1</p>
<p>지금까지 공부한 명령어를 사용하여 다음과 같은 배열을 만들어라.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">array</span><span class="p">([[</span>   <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">],</span>
       <span class="p">[</span>   <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">],</span>
       <span class="p">[</span>   <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">],</span>
       <span class="p">[</span>  <span class="mf">10.</span><span class="p">,</span>   <span class="mf">20.</span><span class="p">,</span>   <span class="mf">30.</span><span class="p">,</span>   <span class="mf">40.</span><span class="p">,</span>   <span class="mf">50.</span><span class="p">],</span>
       <span class="p">[</span>  <span class="mf">60.</span><span class="p">,</span>   <span class="mf">70.</span><span class="p">,</span>   <span class="mf">80.</span><span class="p">,</span>   <span class="mf">90.</span><span class="p">,</span>  <span class="mf">100.</span><span class="p">],</span>
       <span class="p">[</span> <span class="mf">110.</span><span class="p">,</span>  <span class="mf">120.</span><span class="p">,</span>  <span class="mf">130.</span><span class="p">,</span>  <span class="mf">140.</span><span class="p">,</span>  <span class="mf">150.</span><span class="p">],</span>
       <span class="p">[</span>   <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">],</span>
       <span class="p">[</span>   <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">],</span>
       <span class="p">[</span>   <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">],</span>
       <span class="p">[</span>  <span class="mf">10.</span><span class="p">,</span>   <span class="mf">20.</span><span class="p">,</span>   <span class="mf">30.</span><span class="p">,</span>   <span class="mf">40.</span><span class="p">,</span>   <span class="mf">50.</span><span class="p">],</span>
       <span class="p">[</span>  <span class="mf">60.</span><span class="p">,</span>   <span class="mf">70.</span><span class="p">,</span>   <span class="mf">80.</span><span class="p">,</span>   <span class="mf">90.</span><span class="p">,</span>  <span class="mf">100.</span><span class="p">],</span>
       <span class="p">[</span> <span class="mf">110.</span><span class="p">,</span>  <span class="mf">120.</span><span class="p">,</span>  <span class="mf">130.</span><span class="p">,</span>  <span class="mf">140.</span><span class="p">,</span>  <span class="mf">150.</span><span class="p">]])</span>
</pre></div>

In [50]:
zeros = np.zeros([3, 3])
ones = np.ones([3, 2])
numbers = np.reshape(np.arange(10, 160, 10), (3, -1))
res = np.tile(np.vstack([np.hstack([zeros, ones]), numbers]), (2, 1))
res

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

## 2차원 그리드 포인트 생성

In [43]:
x = np.arange(3)
x

array([0, 1, 2])

In [44]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [45]:
X, Y = np.meshgrid(x,y)

In [46]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [47]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [48]:
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

# 배열의 연산

## 벡터화 연산

In [51]:
x = np.arange(1,10001)
y = np.arange(10001,20001)

In [52]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

Wall time: 6.98 ms


In [53]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [54]:
z

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

In [55]:
%%time
z = x + y

Wall time: 0 ns


In [56]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [57]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])


In [58]:
a == b

array([False,  True, False,  True])

In [59]:
a >= b

array([False,  True,  True,  True])

In [60]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
c = np.array([1,2,3,4])

In [61]:
np.all(a==b)

False

In [62]:
np.all(a==c)

True

In [64]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [65]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [66]:
10 ** a

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [67]:
np.log(a + 1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

## 스칼라와 벡터/행렬의 곱셈

In [68]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [70]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

## 브로드캐스팅

In [72]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [77]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [78]:
x + y

array([1, 2, 3, 4, 5])

In [79]:
x + 1

array([1, 2, 3, 4, 5])

In [80]:
x = np.vstack([range(7)[i:i + 3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [81]:
y = np.arange(5)[:, np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [82]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [83]:
y = np.arange(3)
y

array([0, 1, 2])

In [84]:
x + y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

## 차원 축소 연산

In [85]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [86]:
np.sum(x)

10

In [87]:
x.sum()

10

In [88]:
x = np.array([1,3,2])
x

array([1, 3, 2])

In [89]:
x.min()

1

In [90]:
x.max()

3

In [92]:
x.argmin()
#최솟값의 위치

0

In [93]:
x.argmax()
#최댓값의 위치

1

In [94]:
x = np.array([1,2,3,1])
x

array([1, 2, 3, 1])

In [95]:
x.mean()

1.75

In [96]:
np.median(x)

1.5

## 정렬

In [97]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [98]:
np.sort(a)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [99]:
np.sort(a, axis = 0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [100]:
a.sort(axis=1)
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [101]:
a = np.array([42,38,12,25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [102]:
a[j]

array([12, 25, 38, 42])

In [103]:
np.sort(a)

array([12, 25, 38, 42])