In [1]:
import numpy as np

# 기술 통계

In [2]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [3]:
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
         2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [4]:
len(x)

26

In [5]:
np.mean(x)

4.8076923076923075

In [6]:
np.var(x)

115.23224852071006

In [7]:
np.std(x)

10.734628476137871

In [8]:
np.max(x)

23

In [10]:
np.min(x)

-24

In [11]:
np.median(x)

5.0

# 난수 발생과 카운팅

## 시드 설정하기

In [12]:
np.random.seed(0)

In [13]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [14]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [15]:
np.random.seed(0)

In [16]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [19]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [20]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [21]:
np.random.rand(10)

array([0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194,
       0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ])

In [22]:
np.random.rand(10)

array([0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ,
       0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672])

## 데이터 순서 바꾸기

In [24]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.random.shuffle(x)

In [26]:
x

array([5, 6, 8, 1, 4, 9, 0, 3, 2, 7])

## 데이터 샘플링

In [28]:
np.random.choice(5,5,replace=False)

array([1, 4, 2, 0, 3])

In [29]:
np.random.choice(5,3,replace=False)

array([1, 2, 0])

In [30]:
np.random.choice(5,10)

array([4, 0, 4, 3, 2, 0, 1, 1, 3, 0])

In [32]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])

array([3, 0, 3, 3, 3, 3, 3, 0, 3, 0])

## 난수 생성

In [33]:
np.random.rand(10)

array([0.44171092, 0.97958673, 0.35944446, 0.48089353, 0.68866118,
       0.88047589, 0.91823547, 0.21682214, 0.56518887, 0.86510256])

In [34]:
np.random.rand(3,5)

array([[0.50896896, 0.91672295, 0.92115761, 0.08311249, 0.27771856],
       [0.0093567 , 0.84234208, 0.64717414, 0.84138612, 0.26473016],
       [0.39782075, 0.55282148, 0.16494046, 0.36980809, 0.14644176]])

In [36]:
np.random.randn(10)

array([ 1.73719932,  0.59361275, -0.54236358, -1.71967238, -0.57890879,
        1.42694855,  0.27699691,  0.78966713,  0.32207411,  0.70039238])

In [38]:
np.random.randn(3, 5)

array([[ 2.32773811,  1.80440397, -0.24942133, -0.82086383, -1.49333996],
       [ 0.52417595,  0.34511317,  0.72437468, -2.04038084, -1.0797781 ],
       [-0.69342441, -2.33804615,  1.66226234, -0.27535274, -0.74657045]])

## 정수 데이터 카운팅

In [39]:
np.unique([11,11,2,2,34,34])

array([ 2, 11, 34])

In [40]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [41]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [42]:
count

array([2, 2, 1], dtype=int64)

In [43]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0], dtype=int64)