# 3.1 넘파이 배열

<p class="admonition-title">연습 문제 1</p>
<p>넘파이를 사용하여 다음과 같은 행렬을 만든다.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="mi">10</span> <span class="mi">20</span> <span class="mi">30</span> <span class="mi">40</span>
<span class="mi">50</span> <span class="mi">60</span> <span class="mi">70</span> <span class="mi">80</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="id6">

In [3]:
import numpy as np

In [4]:
d = np.array([[10,20,30,40],[50,60,70,80]])
d

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

<p class="admonition-title">연습 문제 2</p>
<p>다음 행렬과 같은 행렬이 있다.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">m</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">array</span><span class="p">([[</span> <span class="mi">0</span><span class="p">,</span>  <span class="mi">1</span><span class="p">,</span>  <span class="mi">2</span><span class="p">,</span>  <span class="mi">3</span><span class="p">,</span>  <span class="mi">4</span><span class="p">],</span>
            <span class="p">[</span> <span class="mi">5</span><span class="p">,</span>  <span class="mi">6</span><span class="p">,</span>  <span class="mi">7</span><span class="p">,</span>  <span class="mi">8</span><span class="p">,</span>  <span class="mi">9</span><span class="p">],</span>
            <span class="p">[</span><span class="mi">10</span><span class="p">,</span> <span class="mi">11</span><span class="p">,</span> <span class="mi">12</span><span class="p">,</span> <span class="mi">13</span><span class="p">,</span> <span class="mi">14</span><span class="p">]])</span>
</pre></div>
</div>
<ol class="simple">
<li><p>이 행렬에서 값 7 을 인덱싱한다.</p></li>
<li><p>이 행렬에서 값 14 을 인덱싱한다.</p></li>
<li><p>이 행렬에서 배열 [6, 7] 을 슬라이싱한다.</p></li>
<li><p>이 행렬에서 배열 [7, 12] 을 슬라이싱한다.</p></li>
<li><p>이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.</p></li>

In [5]:
m = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])

In [6]:
#1
m[1,2]

7

In [7]:
#2
m[-1,-1]

14

In [8]:
#3
m[1,1:3]

array([6, 7])

In [9]:
#4
m[1:,2]

array([ 7, 12])

In [10]:
#5
m[:2,3:]

array([[3, 4],
       [8, 9]])

<p class="admonition-title">연습 문제 3</p>
<p>다음 행렬과 같은 배열이 있다.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">x</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">array</span><span class="p">([</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">5</span><span class="p">,</span> <span class="mi">6</span><span class="p">,</span> <span class="mi">7</span><span class="p">,</span> <span class="mi">8</span><span class="p">,</span> <span class="mi">9</span><span class="p">,</span> <span class="mi">10</span><span class="p">,</span>
             <span class="mi">11</span><span class="p">,</span> <span class="mi">12</span><span class="p">,</span> <span class="mi">13</span><span class="p">,</span> <span class="mi">14</span><span class="p">,</span> <span class="mi">15</span><span class="p">,</span> <span class="mi">16</span><span class="p">,</span> <span class="mi">17</span><span class="p">,</span> <span class="mi">18</span><span class="p">,</span> <span class="mi">19</span><span class="p">,</span> <span class="mi">20</span><span class="p">])</span>
</pre></div>
</div>
<ol class="simple">
<li><p>이 배열에서 3의 배수를 찾아라.</p></li>
<li><p>이 배열에서 4로 나누면 1이 남는 수를 찾아라.</p></li>
<li><p>이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.</p></li>

In [11]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [12]:
#1
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [13]:
#2
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [14]:
#3
x[(x % 3 == 0)&(x % 4 == 1)]

array([9])

# 3.2 배열의 생성과 변형

<p class="admonition-title">연습 문제 3.2.1</p>
<p>지금까지 공부한 명령어를 사용하여 다음과 같은 배열을 만들어라.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">array</span><span class="p">([[</span>   <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">],</span>
       <span class="p">[</span>   <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">],</span>
       <span class="p">[</span>   <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">],</span>
       <span class="p">[</span>  <span class="mf">10.</span><span class="p">,</span>   <span class="mf">20.</span><span class="p">,</span>   <span class="mf">30.</span><span class="p">,</span>   <span class="mf">40.</span><span class="p">,</span>   <span class="mf">50.</span><span class="p">],</span>
       <span class="p">[</span>  <span class="mf">60.</span><span class="p">,</span>   <span class="mf">70.</span><span class="p">,</span>   <span class="mf">80.</span><span class="p">,</span>   <span class="mf">90.</span><span class="p">,</span>  <span class="mf">100.</span><span class="p">],</span>
       <span class="p">[</span> <span class="mf">110.</span><span class="p">,</span>  <span class="mf">120.</span><span class="p">,</span>  <span class="mf">130.</span><span class="p">,</span>  <span class="mf">140.</span><span class="p">,</span>  <span class="mf">150.</span><span class="p">],</span>
       <span class="p">[</span>   <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">],</span>
       <span class="p">[</span>   <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">],</span>
       <span class="p">[</span>   <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">],</span>
       <span class="p">[</span>  <span class="mf">10.</span><span class="p">,</span>   <span class="mf">20.</span><span class="p">,</span>   <span class="mf">30.</span><span class="p">,</span>   <span class="mf">40.</span><span class="p">,</span>   <span class="mf">50.</span><span class="p">],</span>
       <span class="p">[</span>  <span class="mf">60.</span><span class="p">,</span>   <span class="mf">70.</span><span class="p">,</span>   <span class="mf">80.</span><span class="p">,</span>   <span class="mf">90.</span><span class="p">,</span>  <span class="mf">100.</span><span class="p">],</span>
       <span class="p">[</span> <span class="mf">110.</span><span class="p">,</span>  <span class="mf">120.</span><span class="p">,</span>  <span class="mf">130.</span><span class="p">,</span>  <span class="mf">140.</span><span class="p">,</span>  <span class="mf">150.</span><span class="p">]])</span>
</pre></div>

In [16]:
zeros = np.zeros([3, 3])
ones = np.ones([3, 2])
numbers = np.reshape(np.arange(10, 160, 10), (3, -1))
res = np.tile(np.vstack([np.hstack([zeros, ones]), numbers]), (2, 1))
res

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

# 3.3 배열의 연산

<p class="admonition-title">연습 문제 3.3.1</p>
<p>실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.</p>
<ol class="simple">
<li><p>전체의 최댓값</p></li>
<li><p>각 행의 합</p></li>
<li><p>각 행의 최댓값</p></li>
<li><p>각 열의 평균</p></li>
<li><p>각 열의 최솟값</p></li>
</ol>
</div>
</div>

In [17]:
a = np.array([[1,2,3,4,5,6],
             [7,8,9,10,11,12],
             [13,14,15,16,17,18],
             [19,20,21,22,23,24],
             [25,26,27,28,29,30]])
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [20]:
#1
a.max()

30

In [22]:
#2
a.sum(axis=1)

array([ 21,  57,  93, 129, 165])

In [27]:
#3
a.max(axis=1)

array([ 6, 12, 18, 24, 30])

In [26]:
#4
a.mean(axis=1)

array([ 3.5,  9.5, 15.5, 21.5, 27.5])

In [25]:
#5
a.min(axis=0)

array([1, 2, 3, 4, 5, 6])

<p class="admonition-title">연습 문제 3.3.2</p>
<p>다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하라.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">array</span><span class="p">([[</span>  <span class="mi">1</span><span class="p">,</span>    <span class="mi">2</span><span class="p">,</span>    <span class="mi">3</span><span class="p">,</span>    <span class="mi">4</span><span class="p">],</span>
       <span class="p">[</span> <span class="mi">46</span><span class="p">,</span>   <span class="mi">99</span><span class="p">,</span>  <span class="mi">100</span><span class="p">,</span>   <span class="mi">71</span><span class="p">],</span>
       <span class="p">[</span> <span class="mi">81</span><span class="p">,</span>   <span class="mi">59</span><span class="p">,</span>   <span class="mi">90</span><span class="p">,</span>  <span class="mi">100</span><span class="p">]])</span>
</pre></div>
</div>
</div>

In [21]:
x = np.array([[ 1, 2, 3, 4],
[ 46, 99, 100, 71],
[ 81, 59, 90, 100]])
j=x[1,:].argsort()
np.array([x[i,j] for i in range(3)])

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

# 3.5 난수 발생과 카운팅

<p class="admonition-title">연습 문제 3.5.1</p>
<ol class="simple">
<li><p>동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.</p></li>
<li><p>주사위를 100번 던져서 나오는 숫자의 평균을 구하라.</p></li>
</ol>
</div>
<div class="admonition- admonition">

In [30]:
#1
a = np.random.choice(2,10,p=[0.5,0.5])
a


array([1, 1, 1, 0, 0, 0, 0, 1, 1, 1])

In [31]:
#2
a = np.random.randint(1,7,100)
a.mean()

3.4

<p class="admonition-title">연습 문제 3.5.2</p>
<p>가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자.
250일 동안의 주가를 무작위로 생성하라</p>
</div>
</div>

In [37]:
np.random.seed(0)
a=np.random.randn(250)
percent=a/100
result=[10000+percent[0]*10000]
for i in range(1,len(percent)):
    price=result[i-1]+result[i-1]*percent[i]
    result.append(price)
print(result)

[10176.405234596767, 10217.126853695665, 10317.125755097051, 10548.321524496083, 10745.317545953518, 10640.305934454434, 10741.398248726973, 10725.140368205562, 10714.070001464253, 10758.061812386894, 10773.55810880915, 10930.235110142823, 11013.418322778272, 11026.818901338936, 11075.762896183403, 11112.719873528811, 11278.752695617832, 11255.613402413064, 11290.85109259871, 11194.416414485922, 10908.624103482038, 10979.924899129086, 11074.839344564745, 10992.645760883175, 11242.151846339399, 11078.649848799967, 11083.719274707797, 11062.972342243344, 11232.543282795474, 11397.589642604074, 11415.249914346789, 11458.418111041767, 11356.69190814807, 11131.7389559244, 11093.010283665468, 11110.354090886578, 11247.043741862606, 11382.275929398731, 11338.1893222928, 11303.913664106069, 11185.386142212461, 11026.551652650312, 10838.40888874727, 11049.841902583566, 10993.526142246941, 10945.36632937685, 10808.24328786195, 10892.276337059926, 10716.486123706052, 10693.68784109739, 10597.9294