In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
mpl.rc('font', family = 'Gulim')
mpl.rcParams['axes.unicode_minus']=False
import matplotlib.tri as mtri

<p class="admonition-title">연습 문제 1</p>
<p>넘파이를 사용하여 다음과 같은 행렬을 만든다.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="mi">10</span> <span class="mi">20</span> <span class="mi">30</span> <span class="mi">40</span>
<span class="mi">50</span> <span class="mi">60</span> <span class="mi">70</span> <span class="mi">80</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="id6">

In [3]:
np.array([[10,20,30,40],[50,60,70,80]])

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

<p class="admonition-title">연습 문제 2</p>
<p>다음 행렬과 같은 행렬이 있다.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">m</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">array</span><span class="p">([[</span> <span class="mi">0</span><span class="p">,</span>  <span class="mi">1</span><span class="p">,</span>  <span class="mi">2</span><span class="p">,</span>  <span class="mi">3</span><span class="p">,</span>  <span class="mi">4</span><span class="p">],</span>
            <span class="p">[</span> <span class="mi">5</span><span class="p">,</span>  <span class="mi">6</span><span class="p">,</span>  <span class="mi">7</span><span class="p">,</span>  <span class="mi">8</span><span class="p">,</span>  <span class="mi">9</span><span class="p">],</span>
            <span class="p">[</span><span class="mi">10</span><span class="p">,</span> <span class="mi">11</span><span class="p">,</span> <span class="mi">12</span><span class="p">,</span> <span class="mi">13</span><span class="p">,</span> <span class="mi">14</span><span class="p">]])</span>
</pre></div>
</div>
<ol class="simple">
<li><p>이 행렬에서 값 7 을 인덱싱한다.</p></li>
<li><p>이 행렬에서 값 14 을 인덱싱한다.</p></li>
<li><p>이 행렬에서 배열 [6, 7] 을 슬라이싱한다.</p></li>
<li><p>이 행렬에서 배열 [7, 12] 을 슬라이싱한다.</p></li>
<li><p>이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.</p></li>

In [6]:
m = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
m[1,2]

7

In [8]:
m[-1,-1]

14

In [9]:
m[1,1:3]

array([6, 7])

In [10]:
m[1:,2]

array([ 7, 12])

In [11]:
m[:2,3:]

array([[3, 4],
       [8, 9]])

<p class="admonition-title">연습 문제 3</p>
<p>다음 행렬과 같은 배열이 있다.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">x</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">array</span><span class="p">([</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">5</span><span class="p">,</span> <span class="mi">6</span><span class="p">,</span> <span class="mi">7</span><span class="p">,</span> <span class="mi">8</span><span class="p">,</span> <span class="mi">9</span><span class="p">,</span> <span class="mi">10</span><span class="p">,</span>
             <span class="mi">11</span><span class="p">,</span> <span class="mi">12</span><span class="p">,</span> <span class="mi">13</span><span class="p">,</span> <span class="mi">14</span><span class="p">,</span> <span class="mi">15</span><span class="p">,</span> <span class="mi">16</span><span class="p">,</span> <span class="mi">17</span><span class="p">,</span> <span class="mi">18</span><span class="p">,</span> <span class="mi">19</span><span class="p">,</span> <span class="mi">20</span><span class="p">])</span>
</pre></div>
</div>
<ol class="simple">
<li><p>이 배열에서 3의 배수를 찾아라.</p></li>
<li><p>이 배열에서 4로 나누면 1이 남는 수를 찾아라.</p></li>
<li><p>이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.</p></li>

In [13]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [14]:
x[x%3==0]

array([ 3,  6,  9, 12, 15, 18])

In [17]:
x[x%4==1]

array([ 1,  5,  9, 13, 17])

In [18]:
x[(x%3==0)&(x%4==1)]

array([9])

In [19]:
x[(x%3==0)|(x%4==1)]

array([ 1,  3,  5,  6,  9, 12, 13, 15, 17, 18])

<p class="admonition-title">연습 문제 3.2.1</p>
<p>지금까지 공부한 명령어를 사용하여 다음과 같은 배열을 만들어라.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">array</span><span class="p">([[</span>   <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">],</span>
       <span class="p">[</span>   <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">],</span>
       <span class="p">[</span>   <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">],</span>
       <span class="p">[</span>  <span class="mf">10.</span><span class="p">,</span>   <span class="mf">20.</span><span class="p">,</span>   <span class="mf">30.</span><span class="p">,</span>   <span class="mf">40.</span><span class="p">,</span>   <span class="mf">50.</span><span class="p">],</span>
       <span class="p">[</span>  <span class="mf">60.</span><span class="p">,</span>   <span class="mf">70.</span><span class="p">,</span>   <span class="mf">80.</span><span class="p">,</span>   <span class="mf">90.</span><span class="p">,</span>  <span class="mf">100.</span><span class="p">],</span>
       <span class="p">[</span> <span class="mf">110.</span><span class="p">,</span>  <span class="mf">120.</span><span class="p">,</span>  <span class="mf">130.</span><span class="p">,</span>  <span class="mf">140.</span><span class="p">,</span>  <span class="mf">150.</span><span class="p">],</span>
       <span class="p">[</span>   <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">],</span>
       <span class="p">[</span>   <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">],</span>
       <span class="p">[</span>   <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">0.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">,</span>    <span class="mf">1.</span><span class="p">],</span>
       <span class="p">[</span>  <span class="mf">10.</span><span class="p">,</span>   <span class="mf">20.</span><span class="p">,</span>   <span class="mf">30.</span><span class="p">,</span>   <span class="mf">40.</span><span class="p">,</span>   <span class="mf">50.</span><span class="p">],</span>
       <span class="p">[</span>  <span class="mf">60.</span><span class="p">,</span>   <span class="mf">70.</span><span class="p">,</span>   <span class="mf">80.</span><span class="p">,</span>   <span class="mf">90.</span><span class="p">,</span>  <span class="mf">100.</span><span class="p">],</span>
       <span class="p">[</span> <span class="mf">110.</span><span class="p">,</span>  <span class="mf">120.</span><span class="p">,</span>  <span class="mf">130.</span><span class="p">,</span>  <span class="mf">140.</span><span class="p">,</span>  <span class="mf">150.</span><span class="p">]])</span>
</pre></div>

In [23]:
a = np.zeros([3,3])
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
b = np.ones([3,2])
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
c = np.arange(10,160,10).reshape(3,5)
c

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [30]:
e = np.hstack([a,b])
e

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [32]:
f = np.vstack([e,c])
f

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [33]:
result = np.vstack([f,f])
result

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

<p class="admonition-title">연습 문제 3.3.1</p>
<p>실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.</p>
<ol class="simple">
<li><p>전체의 최댓값</p></li>
<li><p>각 행의 합</p></li>
<li><p>각 행의 최댓값</p></li>
<li><p>각 열의 평균</p></li>
<li><p>각 열의 최솟값</p></li>
</ol>
</div>
</div>

In [34]:
x = np.arange(30).reshape(5,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [35]:
x.sum()

435

In [36]:
x.sum(axis=1)

array([ 15,  51,  87, 123, 159])

In [37]:
x.max(axis=1)

array([ 5, 11, 17, 23, 29])

In [38]:
x.mean(axis=0)

array([12., 13., 14., 15., 16., 17.])

In [39]:
x.min(axis=0)

array([0, 1, 2, 3, 4, 5])

<p class="admonition-title">연습 문제 3.3.2</p>
<p>다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하라.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">array</span><span class="p">([[</span>  <span class="mi">1</span><span class="p">,</span>    <span class="mi">2</span><span class="p">,</span>    <span class="mi">3</span><span class="p">,</span>    <span class="mi">4</span><span class="p">],</span>
       <span class="p">[</span> <span class="mi">46</span><span class="p">,</span>   <span class="mi">99</span><span class="p">,</span>  <span class="mi">100</span><span class="p">,</span>   <span class="mi">71</span><span class="p">],</span>
       <span class="p">[</span> <span class="mi">81</span><span class="p">,</span>   <span class="mi">59</span><span class="p">,</span>   <span class="mi">90</span><span class="p">,</span>  <span class="mi">100</span><span class="p">]])</span>
</pre></div>
</div>
</div>

In [54]:
a = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
a

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [55]:
np.sort(a,axis=1)

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])

<p class="admonition-title">연습 문제 3.5.1</p>
<ol class="simple">
<li><p>동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.</p></li>
<li><p>주사위를 100번 던져서 나오는 숫자의 평균을 구하라.</p></li>
</ol>
</div>
<div class="admonition- admonition">

In [46]:
np.random.choice(2,10,p=[0.5,0.5])

array([1, 1, 1, 0, 0, 1, 0, 1, 1, 1])

In [51]:
a = np.random.randint(1,7,100)
a

array([4, 1, 4, 5, 1, 2, 1, 2, 5, 3, 6, 3, 2, 2, 3, 6, 6, 3, 5, 2, 4, 3,
       1, 1, 2, 3, 4, 6, 5, 2, 2, 6, 5, 6, 6, 1, 4, 5, 4, 6, 1, 4, 3, 1,
       1, 6, 6, 6, 2, 4, 4, 6, 2, 3, 6, 4, 2, 6, 6, 4, 5, 6, 3, 3, 4, 1,
       5, 5, 4, 4, 5, 4, 1, 4, 4, 1, 6, 4, 5, 6, 2, 2, 2, 1, 4, 1, 2, 3,
       2, 3, 2, 6, 6, 5, 2, 4, 2, 5, 3, 1])

In [52]:
a.mean()

3.57

<p class="admonition-title">연습 문제 3.5.2</p>
<p>가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자.
250일 동안의 주가를 무작위로 생성하라</p>
</div>
</div>

In [56]:
np.random.seed(0)
a = np.random.randn(250)
a

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ,
        0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
        0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574,
       -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502,  2.26975462,
       -1.45436567,  0.04575852, -0.18718385,  1.53277921,  1.46935877,
        0.15494743,  0.37816252, -0.88778575, -1.98079647, -0.34791215,
        0.15634897,  1.23029068,  1.20237985, -0.38732682, -0.30230275,
       -1.04855297, -1.42001794, -1.70627019,  1.9507754 , -0.50965218,
       -0.4380743 , -1.25279536,  0.77749036, -1.61389785, -0.21274028,
       -0.89546656,  0.3869025 , -0.51080514, -1.18063218, -0.02818223,
        0.42833187,  0.06651722,  0.3024719 , -0.63432209, -0.36274117,
       -0.67246045, -0.35955316, -0.81314628, -1.7262826 ,  0.17742614,
       -0.40178094, -1.63019835,  0.46278226, -0.90729836,  0.05

In [60]:
b = (a*10000+10000)
b

array([ 2.76405235e+04,  1.40015721e+04,  1.97873798e+04,  3.24089320e+04,
        2.86755799e+04,  2.27221201e+02,  1.95008842e+04,  8.48642792e+03,
        8.96781148e+03,  1.41059850e+04,  1.14404357e+04,  2.45427351e+04,
        1.76103773e+04,  1.12167502e+04,  1.44386323e+04,  1.33367433e+04,
        2.49407907e+04,  7.94841736e+03,  1.31306770e+04,  1.45904261e+03,
       -1.55298982e+04,  1.65361860e+04,  1.86443620e+04,  2.57834980e+03,
        3.26975462e+04, -4.54365675e+03,  1.04575852e+04,  8.12816150e+03,
        2.53277921e+04,  2.46935877e+04,  1.15494743e+04,  1.37816252e+04,
        1.12214252e+03, -9.80796468e+03,  6.52087851e+03,  1.15634897e+04,
        2.23029068e+04,  2.20237985e+04,  6.12673183e+03,  6.97697249e+03,
       -4.85529651e+02, -4.20017937e+03, -7.06270191e+03,  2.95077540e+04,
        4.90347818e+03,  5.61925698e+03, -2.52795360e+03,  1.77749036e+04,
       -6.13897848e+03,  7.87259720e+03,  1.04533439e+03,  1.38690250e+04,
        4.89194862e+03, -

<p class="admonition-title">연습 문제 4.1.3</p>
<p>다음 데이터프레임에서 지정하는 데이터를 뽑아내거나 처리하라.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">data</span> <span class="o">=</span> <span class="p">{</span>
    <span class="s2">&quot;국어&quot;</span><span class="p">:</span> <span class="p">[</span><span class="mi">80</span><span class="p">,</span> <span class="mi">90</span><span class="p">,</span> <span class="mi">70</span><span class="p">,</span> <span class="mi">30</span><span class="p">],</span>
    <span class="s2">&quot;영어&quot;</span><span class="p">:</span> <span class="p">[</span><span class="mi">90</span><span class="p">,</span> <span class="mi">70</span><span class="p">,</span> <span class="mi">60</span><span class="p">,</span> <span class="mi">40</span><span class="p">],</span>
    <span class="s2">&quot;수학&quot;</span><span class="p">:</span> <span class="p">[</span><span class="mi">90</span><span class="p">,</span> <span class="mi">60</span><span class="p">,</span> <span class="mi">80</span><span class="p">,</span> <span class="mi">70</span><span class="p">],</span>
<span class="p">}</span>
<span class="n">columns</span> <span class="o">=</span> <span class="p">[</span><span class="s2">&quot;국어&quot;</span><span class="p">,</span> <span class="s2">&quot;영어&quot;</span><span class="p">,</span> <span class="s2">&quot;수학&quot;</span><span class="p">]</span>
<span class="n">index</span> <span class="o">=</span> <span class="p">[</span><span class="s2">&quot;춘향&quot;</span><span class="p">,</span> <span class="s2">&quot;몽룡&quot;</span><span class="p">,</span> <span class="s2">&quot;향단&quot;</span><span class="p">,</span> <span class="s2">&quot;방자&quot;</span><span class="p">]</span>
<span class="n">df</span> <span class="o">=</span> <span class="n">pd</span><span class="o">.</span><span class="n">DataFrame</span><span class="p">(</span><span class="n">data</span><span class="p">,</span> <span class="n">index</span><span class="o">=</span><span class="n">index</span><span class="p">,</span> <span class="n">columns</span><span class="o">=</span><span class="n">columns</span><span class="p">)</span>
</pre></div>
</div>
<p>(1) 모든 학생의 수학 점수를 시리즈로 나타낸다.</p>
<p>(2) 모든 학생의 국어와 영어 점수를 데이터 프레임으로 나타낸다.</p>
<p>(3) 모든 학생의 각 과목 평균 점수를 새로운 열로 추가한다.</p>
<p>(4) 방자의 영어 점수를 80점으로 수정하고 평균 점수도 다시 계산한다.</p>
<p>(5) 춘향의 점수를 데이터프레임으로 나타낸다.</p>
<p>(6) 향단의 점수를 시리즈로 나타낸다.</p>
</div>
</div>

In [63]:
data = {
    "국어":[80,90,70,30],
    "영어":[90,70,60,40],
    "수학":[90,60,80,70]
}
columns = ["국어","영어","수학"]
index = ["춘향","몽룡","향단","방자"]
df = pd.DataFrame(data, index=index, columns=columns)
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [64]:
df["수학"]

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

In [65]:
df[["국어","영어"]]

국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  30  40

In [66]:
df["평균"]=((df["국어"]+df["영어"]+df["수학"])/3)
df

국어  영어  수학         평균
춘향  80  90  90  86.666667
몽룡  90  70  60  73.333333
향단  70  60  80  70.000000
방자  30  40  70  46.666667

In [71]:
df.loc["방자","영어"]=80
df["평균"]=((df["국어"]+df["영어"]+df["수학"])/3)
df

국어  영어  수학         평균
춘향  80  90  90  86.666667
몽룡  90  70  60  73.333333
향단  70  60  80  70.000000
방자  30  80  70  60.000000

In [81]:
df[:2]

국어  영어  수학         평균
춘향  80  90  90  86.666667
몽룡  90  70  60  73.333333

In [76]:
df.iloc[2]

국어    70.0
영어    60.0
수학    80.0
평균    70.0
Name: 향단, dtype: float64

In [82]:
import seaborn as sns
titanic = sns.load_dataset("titanic")
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

<p class="admonition-title">연습 문제 4.4.1</p>
<p>타이타닉호 승객 데이터의 데이터 개수를 각 열마다 구해본다.</p>
</div>

In [83]:
titanic.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

<p class="admonition-title">연습 문제 4.4.2</p>
<p><code class="docutils literal notranslate"><span class="pre">sort_values</span></code> 메서드를 사용하여 타이타닉호 승객에 대해 성별(sex) 인원수, 나이별(age) 인원수, 선실별(class) 인원수, 사망/생존(alive) 인원수를 구하라.</p>
</div>

In [84]:
titanic.sex.value_counts().sort_values()

female    314
male      577
Name: sex, dtype: int64

In [85]:
titanic.age.value_counts().sort_values()

74.00     1
34.50     1
0.42      1
0.67      1
66.00     1
         ..
28.00    25
19.00    25
18.00    26
22.00    27
24.00    30
Name: age, Length: 88, dtype: int64

<p class="admonition-title">연습 문제 4.4.3</p>
<ol class="simple">
<li><p>타이타닉호 승객의 평균 나이를 구하라.</p></li>
<li><p>타이타닉호 승객중 여성 승객의 평균 나이를 구하라.</p></li>
<li><p>타이타닉호 승객중 1등실 선실의 여성 승객의 평균 나이를 구하라.</p></li>
</ol>
</div>

In [96]:
round(titanic.age.mean())

30

In [98]:
titanic_female = titanic[titanic["sex"] == "female"]
a = round(titanic_female["age"].mean())
a

28

In [99]:
titanic_first_female = titanic[(titanic["class"] == "First") & (titanic["sex"] == "female")]
a = round(titanic_first_female["age"].mean())
a

35

<p class="admonition-title">연습 문제 4.4.4</p>
<p>타이타닉호의 승객에 대해 나이와 성별에 의한 카테고리 열인 <code class="docutils literal notranslate"><span class="pre">category1</span></code> 열을 만들어라. <code class="docutils literal notranslate"><span class="pre">category1</span></code> 카테고리는 다음과 같이 정의된다.</p>
<ol class="simple">
<li><p>20살이 넘으면 성별을 그대로 사용한다.</p></li>
<li><p>20살 미만이면 성별에 관계없이 “child”라고 한다.</p></li>
</ol>
</div>

In [100]:
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [104]:
titanic['category1'] = titanic.apply(lambda x: x.sex if x.age>=20 else 'child', axis=1)
titanic[['category1']]

category1
0        male
1      female
2      female
3      female
4        male
..        ...
886      male
887     child
888     child
889      male
890      male

[891 rows x 1 columns]

In [105]:
from ProjectEuler import *

In [107]:
EulerT(1)

In [109]:
num = 1000
rtv = 0
for n in range(1,num):
    if (n%3 == 0) | (n%5 == 0) :
        rtv = rtv + n
print(rtv)

233168


In [110]:
def compute(n):
    ans = sum(x for x in range(1,n) if (x%3==0 | x%5 == 0))
    return ans


In [111]:
compute(1000)

33165

In [112]:
compute(10000000)

3333331666665

In [113]:
EulerT(2)

In [115]:
n = 4000000
ans = 0
fp = 1
fn = 2
while fp <=n:
    if fp%2 == 0:
        ans += fp
    fp, fn = fn, fp +fn
ans

4613732

In [116]:
def coumpute(n):
    x,y,ans = 1,2,0
    while x <= n:
        if x % 2 == 0:
            ans += x
        x,y = y, x+y
    return ans


In [118]:
compute(4000000)

533332666665

In [119]:
EulerT(3)

In [122]:
n,m = 13195,2
while n>1:
    if (n%m) == 0:
        n = n//m
    else:
        m+=1
print(m)

29
